### ISSUE TITLE
Video data for MTM-1 dataset

### ISSUE THREAD

**Issue by LukasHedegaard** [alexriedel1/Hand-Gesture-Recognition-in-manual-assembly-tasks-using-GCN#1]
Thanks for open-sourcing the project!
While it's nice that you have pre-extracted hand-skeleton data, it would be really great, if you could share the raw video data as well 🙏.

Best regards
Lukas

**Comment by alexriedel1** [comment]
Hey Lukas, 
I uploaded a dataset folder where there is each video, the corresponding annotation and the graph data extracted in different augmentations. You can find the details now in the Data section of this repo: 
https://github.com/alexriedel1/Hand-Gesture-Recognition-in-manual-assembly-tasks-using-GCN#data

**Comment by LukasHedegaard** [comment]
Awesome, thank you for the quick response!
Does the dataset have a GNU General Public License v3.0 like the code?

**Comment by alexriedel1** [comment]
> Awesome, thank you for the quick response! Does the dataset have a GNU General Public License v3.0 like the code?

Right, exactly

**Comment by LukasHedegaard** [comment]
Thanks!
