### ISSUE TITLE
Issue with Inference mode

### ISSUE THREAD

**Issue by MBuxel** [alexriedel1/Hand-Gesture-Recognition-in-manual-assembly-tasks-using-GCN#2]
When i run the inference mode most of the predicted labels are wrong, on the other hand when i run the eval i get exactly the same results as you. Is it the same for you? And is there an explanation for that?

**Comment by alexriedel1** [comment]
Hi,
yes looks like validation video 23 which you were runnig inference on is showing a bad performance. I have updated the repo and added some more validation videos with video 2.mp4 being the default now. The predictions on this look a bit better. Also try running the `inference_aug.py ` which includes test time augmentations, being a bit slower but more accurate in its predictions

**Comment by MBuxel** [comment]
Thanks for the quick reply. Also your figure 6 in the paper, how exactly did you create it? Is it the difference of one of the subset adjacency matrices of the in going matrix and the last layer or a combined version of all three subsets?

**Comment by alexriedel1** [comment]
It is the difference between the learned adjacency matrix of the last network layer after 13 epochs of training and the  pre-defined adjacency matrix

**Comment by MBuxel** [comment]
Sure, just to be clear for me. You take the pre-defined adjacency matrix, split it into three subsets: "(1) the inward-links starting from the wrist joint, (2) the outward links pointing in the opposite direction, and (3) the self-links of each joint"  like in your paper said , then you take the new learned adjacency matrices of those three subsets and put them back together to one? How exactly do you put them back together? Or is it just the difference between pre-defined adjacency matrix and the learned adjacency matrix after the last layer of subset 1 for example, the inward-links?

**Comment by alexriedel1** [comment]
The pre-defined adjacency matrix is the full matrix in this case (like in fig 4 in the paper). The matrix is defined here https://github.com/alexriedel1/Hand-Gesture-Recognition-in-manual-assembly-tasks-using-GCN/blob/main/utils/adj_mat.py

inward-links are the original links, outward-links are the same links just in the opposite direction and self-links are self-links. These combined together equal the pre-defined adjacency matrix

**Comment by MBuxel** [comment]
But your model is set by default to the spatial configuration. The default input for your model for the adjacency matrix will be 3x21x21 matrices, representing the different subsets, also your output will be 3x21x21 representing the learned adjacency matrices for the subsets. So you just at those 3 learned adjacency matrices for the last layer together? Or did you not use the spatial mode for the figure?

**Comment by alexriedel1** [comment]
Ahh ok now I got it! The figure was made using the inward-links.

**Comment by alexriedel1** [comment]
Do you need the code for creating the graphic?

**Comment by MBuxel** [comment]
Perfect thanks. No need for the code, I already implemented something like that. I just wanted to know if you were using a subset or not.
